version: '3.8'

services:
  backend:
    container_name: admin-events-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./admin_events_api-main/iwellness_admin_events_api.db:/iwellness_admin_events_api.db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tesisNetwork
networks:
  tesisNetwork:
    external: true